### ISSUE TITLE
Redirection issue

### ISSUE THREAD

**Issue by matricali** [phalcon/documentation#5] opened 2023-12-26 03:14 UTC
A google result that points to: https://docs.phalcon.io/4.0/en/request

Redirects to:
https://docs.phalcon.io/4.0/en/latest

Then:
https://docs.phalcon.io/4.0/en/latest/latest

And so on...

This is the HTML code of the response

```html
</html>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Redirecting...</title>
    <link rel="canonical" href="[introduction/](https://docs.phalcon.io/4.0/en/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/introduction/)">
    <meta name="robots" content="noindex">
    <script type="40f3ffd8f1a388e8749b5a2e-text/javascript">var anchor=window.location.hash.substr(1);location.href="latest/"+(anchor?"#"+anchor:"")</script>
    <meta http-equiv="refresh" content="0; url=latest/">
</head>
<body>
Redirecting...
<script src="[/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js](https://docs.phalcon.io/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js)" data-cf-settings="40f3ffd8f1a388e8749b5a2e-|49" defer></script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317" integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA==" data-cf-beacon='{"rayId":"83b620dd3a1cba74","version":"2023.10.0","token":"359d3a5d34364ab7a64449d1a12ed6f4"}' crossorigin="anonymous"></script>
</body>
</html>
```

**Comment by niden** [comment] 2023-12-26 12:42
Thank you. We are working on it. In the meantime if you want the docs for v4 you can go directly to this URL and navigate from there

https://docs.phalcon.io/4.2/introduction/

(Note 4.0 does not have docs).

The issue is with the 404 redirects.

**Comment by niden** [comment] 2023-12-26 14:13
OK I think that this has been resolved. Can you check it out and let me know please?

**Comment by niden** [comment] 2024-01-06 22:37
Closing this. If the problem persists please open a new issue.

**Closed as completed by niden** 2024-01-06 22:37 UTC
